apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: eduflow
data:
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
  AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
  AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
  AIRFLOW__CORE__FERNET_KEY: ''
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
  AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  AIRFLOW__WEBSERVER__SECRET_KEY: 'eduflow-secret-key-2026'
  AIRFLOW__LOGGING__BASE_LOG_FOLDER: '/opt/airflow/logs'
  AIRFLOW__LOGGING__REMOTE_LOGGING: 'false'
  KAFKA_BOOTSTRAP_SERVERS: kafka:29092
  DBT_DB_HOST: postgres