eduflow_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_DB_HOST', 'localhost') }}"
      user: airflow
      password: airflow
      port: 5432
      dbname: eduflow_warehouse
      schema: public
      threads: 1